CREATE TABLE "GCG_3876_RTR_BRKDWN"(
 "ROUTER" CHAR(20),
 "SELLING_PRICE" NUMERIC(12,4),
 "MATERIAL_VALUE" NUMERIC(12,4),
 "OUTSIDE_SERVICE" NUMERIC(12,4),
 "SHIPPING" NUMERIC(12,4),
 "LABOR_COST" NUMERIC(12,4),
 "VARIABLE_OVHD" NUMERIC(12,4),
 "TOTAL_VARIABLE_COST" NUMERIC(12,4),
 "CONT_MARGIN" NUMERIC(12,4),
 "FIXED_OVHD" NUMERIC(12,4),
 "TOTAL_COST" NUMERIC(12,4),
 "GROSS_MARGIN" NUMERIC(12,4),
 "SALES_COMMISSION" NUMERIC(12,4));
